version: "3.9"

services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
