import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "../../lib/ApolloWrapper";
import Header from "./components/Header";
import ToastProvider from "./components/Toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ApolloWrapper>
          <ToastProvider>{children}</ToastProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
